#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────────
# pause_gravitino_demo.sh
#
# Scales all workloads in the gravitino namespace to zero so the namespace is
# idle while you replicate the deployment in a new namespace.
#
# To resume everything later, run: scripts/resume_gravitino_demo.sh
# (generated alongside this script)
# ──────────────────────────────────────────────────────────────────────────────

set -euo pipefail

NAMESPACE="gravitino"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
RESUME_SCRIPT="${SCRIPT_DIR}/resume_gravitino_demo.sh"

GREEN='\033[0;32m'; BLUE='\033[0;34m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()    { echo -e "${BLUE}[INFO]${NC} $*"; }
success() { echo -e "${GREEN}[OK]${NC}   $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $*"; }

echo ""
echo "════════════════════════════════════════════════════════════════════════════"
echo " Pausing all workloads in namespace: ${NAMESPACE}"
echo "════════════════════════════════════════════════════════════════════════════"

# ── Deployments ───────────────────────────────────────────────────────────────
info "Scaling Deployments to 0..."
kubectl get deployments -n "${NAMESPACE}" -o name | while read -r dep; do
  kubectl scale "${dep}" -n "${NAMESPACE}" --replicas=0
  success "${dep} → 0"
done

# ── StatefulSets ──────────────────────────────────────────────────────────────
info "Scaling StatefulSets to 0..."
kubectl get statefulsets -n "${NAMESPACE}" -o name | while read -r sts; do
  kubectl scale "${sts}" -n "${NAMESPACE}" --replicas=0
  success "${sts} → 0"
done

# ── DaemonSets ────────────────────────────────────────────────────────────────
# DaemonSets cannot be scaled directly — pause by adding a non-matching
# nodeSelector so no node satisfies the scheduling constraint.
info "Pausing DaemonSets (non-matching nodeSelector)..."
kubectl get daemonsets -n "${NAMESPACE}" -o name | while read -r ds; do
  kubectl patch "${ds}" -n "${NAMESPACE}" \
    --type='json' \
    -p='[{"op":"add","path":"/spec/template/spec/nodeSelector","value":{"paused":"true"}}]'
  success "${ds} → paused (nodeSelector: paused=true)"
done

# ── Generate companion resume script ─────────────────────────────────────────
info "Writing resume script → ${RESUME_SCRIPT}"

cat > "${RESUME_SCRIPT}" <<'RESUME'
#!/usr/bin/env bash
# Auto-generated by pause_gravitino_demo.sh — restores all workloads to 1 replica.

set -euo pipefail

NAMESPACE="gravitino"

GREEN='\033[0;32m'; BLUE='\033[0;34m'; NC='\033[0m'
info()    { echo -e "${BLUE}[INFO]${NC} $*"; }
success() { echo -e "${GREEN}[OK]${NC}   $*"; }

echo ""
echo "════════════════════════════════════════════════════════════════════════════"
echo " Resuming all workloads in namespace: ${NAMESPACE}"
echo "════════════════════════════════════════════════════════════════════════════"

info "Scaling Deployments to 1..."
kubectl get deployments -n "${NAMESPACE}" -o name | while read -r dep; do
  kubectl scale "${dep}" -n "${NAMESPACE}" --replicas=1
  success "${dep} → 1"
done

info "Scaling StatefulSets to 1..."
kubectl get statefulsets -n "${NAMESPACE}" -o name | while read -r sts; do
  kubectl scale "${sts}" -n "${NAMESPACE}" --replicas=1
  success "${sts} → 1"
done

info "Unpausing DaemonSets (removing nodeSelector)..."
kubectl get daemonsets -n "${NAMESPACE}" -o name | while read -r ds; do
  kubectl patch "${ds}" -n "${NAMESPACE}" \
    --type='json' \
    -p='[{"op":"remove","path":"/spec/template/spec/nodeSelector"}]' \
    2>/dev/null || \
  kubectl patch "${ds}" -n "${NAMESPACE}" \
    --type='json' \
    -p='[{"op":"replace","path":"/spec/template/spec/nodeSelector","value":{}}]'
  success "${ds} → unpaused"
done

echo ""
echo "════════════════════════════════════════════════════════════════════════════"
echo " Done. Waiting for pods to become Ready..."
echo "════════════════════════════════════════════════════════════════════════════"
kubectl wait pod -n "${NAMESPACE}" --all --for=condition=Ready --timeout=180s 2>/dev/null || true
kubectl get pods -n "${NAMESPACE}"
RESUME

chmod +x "${RESUME_SCRIPT}"

echo ""
echo "════════════════════════════════════════════════════════════════════════════"
echo " Done. All workloads in '${NAMESPACE}' are paused."
echo ""
echo "   Resume when ready:  bash scripts/resume_gravitino_demo.sh"
echo "════════════════════════════════════════════════════════════════════════════"
