#!/usr/bin/env bash
# Auto-generated by pause_gravitino_demo.sh — restores all workloads to 1 replica.

set -euo pipefail

NAMESPACE="gravitino"

GREEN='\033[0;32m'; BLUE='\033[0;34m'; NC='\033[0m'
info()    { echo -e "${BLUE}[INFO]${NC} $*"; }
success() { echo -e "${GREEN}[OK]${NC}   $*"; }

echo ""
echo "════════════════════════════════════════════════════════════════════════════"
echo " Resuming all workloads in namespace: ${NAMESPACE}"
echo "════════════════════════════════════════════════════════════════════════════"

info "Scaling Deployments to 1..."
kubectl get deployments -n "${NAMESPACE}" -o name | while read -r dep; do
  kubectl scale "${dep}" -n "${NAMESPACE}" --replicas=1
  success "${dep} → 1"
done

info "Scaling StatefulSets to 1..."
kubectl get statefulsets -n "${NAMESPACE}" -o name | while read -r sts; do
  kubectl scale "${sts}" -n "${NAMESPACE}" --replicas=1
  success "${sts} → 1"
done

info "Unpausing DaemonSets (removing nodeSelector)..."
kubectl get daemonsets -n "${NAMESPACE}" -o name | while read -r ds; do
  kubectl patch "${ds}" -n "${NAMESPACE}" \
    --type='json' \
    -p='[{"op":"remove","path":"/spec/template/spec/nodeSelector"}]' \
    2>/dev/null || \
  kubectl patch "${ds}" -n "${NAMESPACE}" \
    --type='json' \
    -p='[{"op":"replace","path":"/spec/template/spec/nodeSelector","value":{}}]'
  success "${ds} → unpaused"
done

echo ""
echo "════════════════════════════════════════════════════════════════════════════"
echo " Done. Waiting for pods to become Ready..."
echo "════════════════════════════════════════════════════════════════════════════"
kubectl wait pod -n "${NAMESPACE}" --all --for=condition=Ready --timeout=180s 2>/dev/null || true
kubectl get pods -n "${NAMESPACE}"
