apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gravitino-storage
  namespace: gravitino-demo
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
